version: '3.8'

services:
  user-service:
    image: nauman920/user-service-be:latest
    container_name: user-service-be
    networks:
         - micro-service
    ports:
      - "5001:5001"
    restart: unless-stopped
    working_dir: /usr/src/app

  product-service:
    image: nauman920/product-service-be:latest
    container_name: product-service-be
    networks:
         - micro-service
    ports:
      - "5002:5002"
    restart: unless-stopped
    working_dir: /app
  frontend:
    image: nauman920/micro-service-frontend:latest
    container_name: frontend
    networks:
         - micro-service
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /app


# Optional: Define a default network (Docker Compose does this automatically)
networks:
  default:
    driver: bridge
